# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mgmt-configs
#   namespace: openshift-gitops
# spec:
#   destination:
#     name: ''
#     namespace: default
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: mgmt/gitops
#     repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
#     targetRevision: HEAD
#     directory:
#       recurse: true
#   project: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-auth
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt/auth
    repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-acm
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt/acm
    repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-other
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt/other
    repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-aap
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ansible-automation-platform
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt/aap
    repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-rhhc-acm
  namespace: openshift-gitops
spec:
  destination:
    namespace: rhhc-acm
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt/rhhc-acm
    repoURL: 'http://gitlocal.wwtatc.lab/wwt/rhhc-cluster-configs'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
