# Create Policies to enforce GitOps to be installed on all clusters for ACM Management
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-installed
  annotations:
    policy.open-cluster-management.io/controls: SC-28 Protection Of Information At Rest
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-installed
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-gitops-installed
                  namespace: openshift-operators
                  labels:
                    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
                spec:
                  name: openshift-gitops-installed
                  channel: stable
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: openshift-gitops-installed
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-installed-placement
spec:
  clusterSelector:
    matchExpressions:
      - key: gitops
        operator: NotIn
        values:
          - "false"
  clusterConditions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-installed-placement
placementRef:
  name: openshift-gitops-installed-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: openshift-gitops-installed
    apiGroup: policy.open-cluster-management.io
    kind: Policy
