# Create Policies to enforce GitOps to be installed on all clusters for ACM Management
# it no deploy right now.. not sure why.
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-installed
  annotations:
    policy.open-cluster-management.io/controls: SC-28 Protection Of Information At Rest
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-installed
        spec:
          remediationAction: enforce
          severity: Medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-gitops-operator
                  namespace: openshift-operators
                spec:
                  name: openshift-gitops-operator
                  channel: stable
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: rhhc-common
                  namespace: openshift-gitops
                spec:
                  destination:
                    namespace: default
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    path: common
                    repoURL: https://github.com/coreywan/rhhc-cluster-configs
                    targetRevision: HEAD
                    directory:
                      recurse: true
                  syncPolicy:
                    automated:
                      selfHeal: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-installed-placement
spec:
  clusterSelector:
    matchExpressions:
      - key: gitops
        operator: NotIn
        values:
          - "false"

      - key: local-cluster
        operator: NotIn
        values:
          - "true"
  clusterConditions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-installed-placement
placementRef:
  name: openshift-gitops-installed-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: openshift-gitops-installed
    apiGroup: policy.open-cluster-management.io
    kind: Policy
