---
apiVersion: v1
kind: Namespace
metadata:
  name: ldap-sync

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
  - apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-group-syncer
subjects:
  - kind: ServiceAccount
    name: ldap-group-syncer
    namespace: ldap-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-group-syncer

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  whitelist.txt: |
    CN=rhhc-admins,OU=groups,DC=wwtatc,DC=local
    CN=rhhc-builders,OU=groups,DC=wwtatc,DC=local
    CN=rhhc-viewers,OU=groups,DC=wwtatc,DC=local
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    url: "ldap://wwtatc.local"        
    insecure: true
    bindDN: "CN=ldap-rhhc,OU=LDAP-BIND,OU=service_accts,DC=wwtatc,DC=local"
    bindPassword:
      file: "/etc/secrets/bindPassword"
    augmentedActiveDirectory:
        groupsQuery:
            baseDN: "ou=groups,dc=wwtatc,dc=local"
            scope: sub
            derefAliases: never
            filter: (objectclass=group)
            pageSize: 0
        groupUIDAttribute: distinguishedName 
        groupNameAttributes: [ cn ] 
        usersQuery:
            baseDN: "dc=wwtatc,dc=local"
            scope: sub
            derefAliases: never
            filter: (objectclass=person)
            pageSize: 0
        userNameAttributes: [ sAMAccountName ] 
        groupMembershipAttributes: [ memberOf ] 

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
spec:                                                                                
  schedule: "*/30 * * * *"                                                           
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800                                                  
      template:
        spec:
          containers:
            - name: ldap-group-sync
              image: "registry.redhat.io/openshift4/ose-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync --sync-config=/etc/config/sync.yaml --whitelist=/etc/config/whitelist.txt --confirm" 
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-syncer"
            - name: "ldap-bind-password"
              secret:
                secretName: "wwtatc-ldap-secret"                                                                                        
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"